### ISSUE TITLE
UUID: consider switching from github.com/pborman/uuid to github.com/google/uuid

### ISSUE THREAD

**Issue by mbana** [go-openapi/strfmt#38]
**From:** https://github.com/pborman/uuid
**To:** https://github.com/google/uuid

The only function that I can see being used from https://github.com/pborman/uuid is `uuid.NewMD5`, see https://github.com/go-openapi/strfmt/search?q=uuid&unscoped_q=uuid.

The implementation of this function in both the uuid packages is the same:

- https://github.com/pborman/uuid/blob/master/hash.go#L43
- https://github.com/google/uuid/blob/master/hash.go#L43

**Comment by fredbi** [comment]
pborman's package looks like it is well maintained and functional. At the moment, it is far more popular than google's package.

Unless you have a specific feature in mind (in this case, feel free to reopen the issue and possibly push a R), I don't see any real value with this move.

**Comment by justincormack** [comment]
pborman maintains google's uuid package, and they have a complicated shared history, but the release notes for pborman/uuid now read

The choice of this package vs the google/uuid package is largely dependent on your use case. If you want to use UUIDs as keys, used the google/uuid version (a UUID is an array). Use this package for compatibility, needing to distinguish between non-set UUID and the zero UUID, prefer byte slices over arrays.

google/uuid is now a dependency of pborman/uuid which is now just a compat wrapper, so it is probably a good idea to switch now, as otherwise you need both. I can open a PR if you like, I have been cleaning up uuid usage in many projects as there are lots of broken packages, and google/uuid seems the best overall choice, for example Kubernetes and Docker both recently switched.

**Comment by fredbi** [comment]
ok
